name: Deploy GitHub Pages

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 12.x
    - run: yarn
    - run: yarn build
    - uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        personal_token: ${{ secrets.ACCESS_TOKEN }}
        publish_dir: packages/website/out
        publish_branch: gh-pages
        cname: croquisjs.0xabcdef.com
        enable_jekyll: false
        keep_files: false
